/**
 * Build script to generate static HTML and markdown for the README page.
 *
 * Reads local README.md, transforms it to HTML with:
 * - Syntax highlighting via highlight.js (bash only)
 * - GitHub-flavored markdown styling
 * - All CSS inlined
 *
 * Exports both HTML and raw markdown with {{BASE_URL}} and {{FINGERPRINT_COMMENT}} placeholders.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { marked } from 'marked';
import { gfmHeadingId } from 'marked-gfm-heading-id';
import markedAlert from 'marked-alert';
import hljs from 'highlight.js/lib/core';
import bash from 'highlight.js/lib/languages/bash';

// Register only bash for minimal bundle size
hljs.registerLanguage('bash', bash);

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = join(__dirname, '..');

// Read source files
const readmeContent = readFileSync(join(ROOT_DIR, 'README.md'), 'utf-8');
const githubMarkdownCss = readFileSync(
  join(ROOT_DIR, 'node_modules/github-markdown-css/github-markdown.css'),
  'utf-8'
);
const highlightLightCss = readFileSync(
  join(ROOT_DIR, 'node_modules/highlight.js/styles/github.min.css'),
  'utf-8'
);
const highlightDarkCss = readFileSync(
  join(ROOT_DIR, 'node_modules/highlight.js/styles/github-dark.min.css'),
  'utf-8'
);

// Apply placeholders to README content
// Replace reprox.dev URLs with {{BASE_URL}} placeholder
let processedMarkdown = readmeContent.replace(/https:\/\/reprox\.dev/g, '{{BASE_URL}}');

// Replace fingerprint verification comment with placeholder
processedMarkdown = processedMarkdown.replace(
  /# Verify the instance's fingerprint by browsing to it in your web browser/g,
  '{{FINGERPRINT_COMMENT}}'
);

// Configure marked with plugins and syntax highlighting
marked.use(gfmHeadingId());
marked.use(markedAlert());
marked.use({
  renderer: {
    code(token) {
      const lang = token.lang || '';
      const code = token.text;

      // Apply syntax highlighting for bash
      if (lang === 'bash' && hljs.getLanguage('bash')) {
        const highlighted = hljs.highlight(code, { language: 'bash' }).value;
        return `<pre><code class="hljs language-bash">${highlighted}</code></pre>`;
      }

      // Fallback for other languages (escape HTML)
      const escaped = code
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
      return `<pre><code class="hljs${lang ? ` language-${lang}` : ''}">${escaped}</code></pre>`;
    },
  },
});

// Render markdown to HTML
const renderedContent = marked.parse(processedMarkdown) as string;

// Build complete HTML document
const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Reprox - A Serverless Github Releases APT/RPM Gateway</title>
  <meta name="description" content="Turn Github Releases into an APT or COPR repository">
  <meta name="keywords" content="linux, software, reprox, github, releases, apt, copr, repository">
  <meta property="og:url" content="{{BASE_URL}}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="Reprox - A Serverless Github Releases APT/RPM Gateway">
  <meta property="og:description" content="Turn Github Releases into an APT or COPR repository">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <style>
${githubMarkdownCss}
  </style>
  <style media="(prefers-color-scheme: light)">
${highlightLightCss}
  </style>
  <style media="(prefers-color-scheme: dark)">
${highlightDarkCss}
  </style>
  <style>
    .markdown-body {
      box-sizing: border-box;
      min-width: 200px;
      max-width: 980px;
      margin: 0 auto;
      padding: 45px;
    }
    @media (max-width: 767px) {
      .markdown-body { padding: 15px; }
    }
  </style>
</head>
<body class="markdown-body">
  <main id="content">
${renderedContent}
  </main>
</body>
</html>`;

// Generate TypeScript file with exported constants
const output = `// Auto-generated by scripts/build-readme.ts - DO NOT EDIT
// Run 'npm run build:readme' to regenerate

export const README_HTML = ${JSON.stringify(html)};

export const README_MARKDOWN = ${JSON.stringify(processedMarkdown)};
`;

// Ensure output directory exists
const outputDir = join(ROOT_DIR, 'src/generated');
mkdirSync(outputDir, { recursive: true });

// Write output
writeFileSync(join(outputDir, 'readme-html.ts'), output, 'utf-8');

console.log('Generated src/generated/readme-html.ts');
